name: ai-ml

on:
  push:
    branches:
      - ci_test

# env:

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Test
        with:
          workdir: ./
          args: do test