name: ai-ml

on:
  push:
    branches:
      - ci_test

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  
jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Test
        uses: dagger/dagger-for-github@v2
        with:
          workdir: ./
          args: do test

      - name: Discord notification

      - name: Discord
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'