name: commit-pipeline


on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!master'


env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}


jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Running Black
        uses: lgeiger/black-action@v1.0.1
        with:
          args: ./src
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Samuel Walker'
          git config --global user.email 'samuel-walker@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
          git commit -am "Automated changes"
          git push
      - name: Discord
        uses: Ilshidur/action-discord@master
        with:
          args: 'Formatting {{ EVENT_PAYLOAD.repository.full_name }} has completed successfully.'