name: commit-pipeline


on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!master'


env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}


jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Black
        run: pip install black
      - name: Running Black
        run: black ./src
      - name: Discord
        uses: Ilshidur/action-discord@master
        with:
          args: 'Formatting for {{ EVENT_PAYLOAD.repository.full_name }} has completed successfully.'