name: ai-ml

on:
  push:
    branches:
      - master

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: execute py script # run the run.py to get the latest data
        run: python util_ci_pipeline.py
      - name: fix coverage.py
        run: python util_correct_sonar_dir.py
      - name: Discord
        uses: Ilshidur/action-discord@master
        with:
          args: 'Python script for {{ EVENT_PAYLOAD.repository.full_name }} has completed successfully.'

  
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Discord
        uses: Ilshidur/action-discord@master
        with:
          args: 'SonarQube for {{ EVENT_PAYLOAD.repository.full_name }} has finished'