name: stop-sonarqube

on:
  schedule:
    - cron: '47 11 * * *'

jobs:
  start_sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Discord
        uses: Ilshidur/action-discord@master
        with:
          args: '@everyone peer team sucks - GitHub Team'